// Runs once a day. Checks every active employee for a birthday or work
// anniversary that matches today, and creates a PENDING award for it —
// a manager still has to approve it in the dashboard before points are
// added and the text goes out. This never auto-texts anyone.
//
// "Today" is always Ottawa time (see lib/time.js), not the server's UTC clock.

const cron = require('node-cron');
const pool = require('../db/pool');
const { TIMEZONE, today, parseDate, isSameMonthDay } = require('./time');

async function checkBirthdaysAndAnniversaries() {
  const now = today();

  const employees = (await pool.query(
    `SELECT * FROM employees WHERE status = 'Active'`
  )).rows;

  const rules = (await pool.query(`SELECT * FROM recognition_rules`)).rows;
  const ruleByEvent = Object.fromEntries(rules.map(r => [r.event, r]));

  for (const emp of employees) {
    if (emp.birthday && isSameMonthDay(emp.birthday, now)) {
      await maybeCreateAward(emp, 'Birthday', ruleByEvent['Birthday'], now);
    }
    if (emp.start_date && isSameMonthDay(emp.start_date, now)) {
      const years = now.year - parseDate(emp.start_date).year;
      if (years >= 1) {
        const label = `${years} Year Anniversary`;
        await maybeCreateAward(emp, label, ruleByEvent[label], now);
      }
    }
  }
}

async function maybeCreateAward(employee, eventLabel, rule, now) {
  // Avoid duplicate awards if the job runs more than once on the same day
  const existing = await pool.query(
    `SELECT id FROM point_transactions
     WHERE employee_id = $1 AND reason = $2
       AND (created_at AT TIME ZONE $3)::date = $4::date`,
    [employee.id, eventLabel, TIMEZONE, now.iso]
  );
  if (existing.rows.length > 0) return;

  // No matching Recognition Rule (e.g. an 11 Year Anniversary): still flag it
  // for a manager, with 0 points. Approving it picks up the points from the
  // rule once someone adds it (see routes/transactions.js).
  const notes = rule
    ? 'Auto-generated by daily check — needs manager approval'
    : `Auto-generated by daily check — there's no "${eventLabel}" rule yet. Add one under Recognition Rules, then approve.`;

  await pool.query(
    `INSERT INTO point_transactions (employee_id, type, reason, points, status, notes)
     VALUES ($1, 'award', $2, $3, 'pending', $4)`,
    [employee.id, eventLabel, rule ? rule.points : 0, notes]
  );
}

function run() {
  checkBirthdaysAndAnniversaries().catch(err => console.error('Birthday/anniversary check failed:', err));
}

function start() {
  // Runs every day at 7:00 AM Ottawa time
  cron.schedule('0 7 * * *', run, { timezone: TIMEZONE });

  // Also check at startup: on Render's free tier the app sleeps when idle and
  // would miss the 7 AM run. The duplicate check above makes this safe.
  run();
}

module.exports = { start, checkBirthdaysAndAnniversaries };
