// Runs once a day. Checks every active employee for a birthday or work
// anniversary that matches today, and creates a PENDING award for it —
// a manager still has to approve it in the dashboard before points are
// added and the text goes out. This never auto-texts anyone.

const cron = require('node-cron');
const pool = require('../db/pool');

async function checkBirthdaysAndAnniversaries() {
  const today = new Date();
  const month = today.getMonth() + 1;
  const day = today.getDate();

  const employees = (await pool.query(
    `SELECT * FROM employees WHERE status = 'Active'`
  )).rows;

  const rules = (await pool.query(`SELECT * FROM recognition_rules`)).rows;
  const ruleByEvent = Object.fromEntries(rules.map(r => [r.event, r]));

  for (const emp of employees) {
    if (emp.birthday) {
      const bday = new Date(emp.birthday);
      if (bday.getMonth() + 1 === month && bday.getDate() === day) {
        await maybeCreateAward(emp, 'Birthday', ruleByEvent['Birthday']);
      }
    }
    if (emp.start_date) {
      const start = new Date(emp.start_date);
      if (start.getMonth() + 1 === month && start.getDate() === day) {
        const years = today.getFullYear() - start.getFullYear();
        if (years >= 1) {
          const label = `${years} Year Anniversary`;
          await maybeCreateAward(emp, label, ruleByEvent[label]);
        }
      }
    }
  }
}

async function maybeCreateAward(employee, eventLabel, rule) {
  if (!rule) return; // no matching entry in Recognition Rules — skip silently

  // Avoid duplicate awards if the job runs more than once on the same day
  const existing = await pool.query(
    `SELECT id FROM point_transactions
     WHERE employee_id = $1 AND reason = $2 AND created_at::date = CURRENT_DATE`,
    [employee.id, eventLabel]
  );
  if (existing.rows.length > 0) return;

  await pool.query(
    `INSERT INTO point_transactions (employee_id, type, reason, points, status, notes)
     VALUES ($1, 'award', $2, $3, 'pending', 'Auto-generated by daily check — needs manager approval')`,
    [employee.id, eventLabel, rule.points]
  );
}

function start() {
  // Runs every day at 7:00 AM server time
  cron.schedule('0 7 * * *', () => {
    checkBirthdaysAndAnniversaries().catch(err => console.error('Cron error:', err));
  });
}

module.exports = { start, checkBirthdaysAndAnniversaries };
